# Generated by Django 5.1.4 on 2024-12-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
